version: '3.8'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: the_eye
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db_admin:/var/lib/mysql
    ports:
      - 8806:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=the_eye
      - DB_USER=root
      - DB_PASS=root
      - DJANGO_SU_NAME=admin
      - DJANGO_SU_EMAIL=carlos_jcez@hotmail.com
      - DJANGO_SU_PASSWORD=123
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py create_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/the_eye
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=the_eye
      - DB_USER=root
      - DB_PASS=root
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: celery --app=api worker --loglevel=info
    volumes:
      - .:/the_eye
    depends_on:
      - db
      - redis

  redis:
    image: redis:6-alpine